version: '3.7'

services:

  express:
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_HOST=database

  database:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017